# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Test

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with black
        run: |
          black --check app
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest --cov=app --cov-report=lcov
